language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - unzip
    - curl
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - uuid-dev
    - zlib1g
os:
  - linux
  - osx
osx_image: xcode7.2
branches:
  only:
    - master
    - dev
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force openssl ; fi

script:
  - ./scripts/travis_install.sh
  - ./scripts/travis_build.sh
  - ./scripts/travis_test.sh
